#!/bin/sh
set -eu

file=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    -f)
      file="$2"
      shift 2
      ;;
    up)
      shift
      break
      ;;
    *)
      shift
      ;;
  esac
done

test -n "$file"
exec /usr/local/bin/jas-base-fixture suite "$file"
