import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { ApiClient, DeploymentDefinition, DeploymentDetail, JsonValue, Operation, RouteHistory, RouterBinding, RouteState } from './api'
import { connectionConsumers, consumedSlots, definitionSpec, resolvedGroups, updateBindingYaml, type ConnectionSpec } from './connectionModel'

type Pending = { consumer: string; oldGroup: string | null; newGroup: string; oldRoutes: Record<string, string>; newRoutes: Record<string, string>; version: number | null }
type Transition = 'close' | 'drain' | 'pin'
type SwitchReport = { consumer: string; succeeded: boolean; detail: string; routes: RouteState | null }
const colors: Record<string, string> = { java: '#2457D6', backend: '#2457D6', python: '#7651C9', suite: '#7651C9', database: '#B25C32' }
const cableColor = (slot: string, protocol = '') => Object.entries(colors).find(([name]) => slot.toLowerCase().includes(name))?.[1] ?? ({ tcp: '#B25C32', grpc: '#7651C9' }[protocol] ?? '#2457D6')
const short = (value?: string | null) => value ? value.slice(0, 9) : 'unknown'
const version = (value: number | null) => value === null ? '—' : `v${value}`
const transitionState = (value: JsonValue) => {
  if (value && typeof value === 'object' && !Array.isArray(value)) {
    for (const key of ['state', 'status', 'strategy']) if (typeof value[key] === 'string') return value[key]
    if (Object.keys(value).length === 0) return 'none'
  }
  return JSON.stringify(value) ?? String(value)
}
const historyFor = (routes: RouteState, binding: RouterBinding) => routes.history.filter((entry) => entry.binding === binding.binding && entry.router === binding.router).slice(-5)
const rollback = (binding: RouterBinding, history: RouteHistory[]) => {
  const recorded = [...history].reverse().find((entry) => entry.activationStatus === 'rolled_back')
  if (recorded) return `rollback recorded at v${recorded.version} (timestamp ${recorded.recordedAt})`
  return binding.previousVersion === null ? 'no rollback recorded' : `previous version v${binding.previousVersion} available for rollback`
}
const operationDetail = (operation: Operation | null) => {
  if (!operation) return 'Operation status unavailable after the switch request.'
  if (operation.error) return `${operation.error.code}: ${operation.error.message}`
  if (operation.result) return `Exit code ${operation.result.exitCode}. ${operation.result.stderr.trim() || operation.result.stdout.trim() || 'No command output.'}`
  return `${operation.kind} ${operation.status}.`
}

export default function DeploymentWorkspace({ detail, selectedInstance, onSelectInstance }: { detail: DeploymentDetail; selectedInstance: string; onSelectInstance: (instance: string) => void }) {
  const [table, setTable] = useState(false)
  const spec = detail.snapshot?.spec ?? {}; const groups = useMemo(() => resolvedGroups(spec.groups), [spec.groups]); const bindings = spec.bindings ?? detail.bindings; const direct = spec.routes ?? {}
  const consumed = consumedSlots(spec)
  const routesFor = (consumer: string, group = bindings[consumer]) => group && groups[group] ? groups[group] : direct[consumer] ?? {}
  const requiredSlotsFor = (consumer: string) => consumed[consumer] ?? Object.keys(routesFor(consumer)); const consumers = connectionConsumers(spec, consumed); const instances = spec.instances ?? Object.keys(detail.sourceIdentities).map((name) => ({ name })); const providers = new Set<string>()
  for (const consumer of consumers) for (const target of Object.values(routesFor(consumer))) providers.add(target.split('/')[0])
  return <>
    <div className="patch-toolbar"><div><h2>Observed runtime patch bay</h2><p className="muted">Observed/runtime state from the applied snapshot.</p></div><label className="check"><input type="checkbox" checked={table} onChange={(event) => setTable(event.target.checked)} />Route matrix table</label></div>
    <div className={table ? 'patch-bay table-mode' : 'patch-bay'}>
      <div className="lane"><h3>UI consumers</h3>{consumers.map((name) => <button className="patch-node" aria-pressed={selectedInstance === name} key={name} onClick={() => onSelectInstance(name)}><strong>{name}</strong><small>{!bindings[name] && consumed[name] ? 'unbound' : detail.sourceIdentities[name]?.commit?.slice(0, 7) ?? 'unknown'}</small></button>)}</div>
      <svg className="cables" role="img" aria-label="Route cables" viewBox="0 0 600 360" preserveAspectRatio="none"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="context-stroke" /></marker></defs>{consumers.flatMap((consumer, ci) => Object.entries(routesFor(consumer)).map(([slot, target], ri) => <path key={`${consumer}-${slot}`} data-slot={slot} aria-label={`${consumer} ${slot} to ${target}`} d={`M 20 ${55 + ci * 72} C 190 ${55 + ci * 72}, 390 ${55 + (ri + ci) * 52}, 580 ${55 + (ri + ci) * 52}`} stroke={cableColor(slot)} markerEnd="url(#arrow)" />))}</svg>
      <div className="lane provider-lane"><h3>Backends & providers</h3>{instances.filter((instance) => providers.has(instance.name)).map((instance) => <button className="patch-node" aria-pressed={selectedInstance === instance.name} key={instance.name} onClick={() => onSelectInstance(instance.name)}><strong>{instance.name}</strong><small>{short(detail.sourceIdentities[instance.name]?.commit)}</small></button>)}</div>
      <div className="lane group-lane"><h3>Provider groups</h3>{Object.entries(groups).map(([name, members]) => <div className="patch-node" key={name}><strong>{name}</strong><small>{Object.keys(members).length} services</small></div>)}</div>
      <table className="route-matrix"><caption>Accessible route matrix</caption><thead><tr><th>Consumer</th><th>Slot</th><th>Provider</th><th>Capability</th></tr></thead><tbody>{consumers.flatMap((consumer) => { const active = routesFor(consumer); return requiredSlotsFor(consumer).map((slot) => <tr key={`${consumer}-${slot}`}><th>{consumer}</th><td><span className="capability-key" style={{ '--capability': cableColor(slot) } as React.CSSProperties} />{slot}</td><td>{active[slot] ?? 'Unbound — no current provider'}</td><td>{active[slot] ? 'compatible' : 'unbound'}</td></tr>) })}</tbody></table>
    </div>
  </>
}

export function InstanceBindingEditor({ client, detail, routes, instance, onOperation, refresh, report }: { client: ApiClient; detail: DeploymentDetail; routes: RouteState | null; instance: string; onOperation: (operation: Operation) => Promise<Operation | null>; refresh: () => Promise<void>; report: (error: unknown) => void }) {
  const [pending, setPending] = useState<Pending | null>(null); const [switchReport, setSwitchReport] = useState<SwitchReport | null>(null); const [transition, setTransition] = useState<Transition>('close'); const [timeout, setTimeoutValue] = useState(30000)
  const spec = detail.snapshot?.spec ?? {}; const groups = resolvedGroups(spec.groups); const bindings = spec.bindings ?? detail.bindings; const direct = spec.routes ?? {}; const consumed = consumedSlots(spec)
  const routesFor = (consumer: string, group = bindings[consumer]) => group && groups[group] ? groups[group] : direct[consumer] ?? {}; const required = consumed[instance] ?? Object.keys(routesFor(instance)); const compatible = Object.entries(groups).filter(([, providers]) => required.every((slot) => slot in providers)).map(([name]) => name)
  const prepare = (newGroup: string) => { const oldRoutes = routesFor(instance); setPending({ consumer: instance, oldGroup: bindings[instance] ?? (Object.keys(oldRoutes).length ? 'direct routes' : null), newGroup, oldRoutes, newRoutes: routesFor(instance, newGroup), version: routes?.bindings.find((route) => route.binding === instance)?.currentVersion ?? null }) }
  const apply = async () => { if (!pending) return; const consumer = pending.consumer; try { const extra: Record<string, unknown> = { consumer, group: pending.newGroup, transition: transition === 'drain' ? { strategy: 'drain', timeoutMs: timeout } : { strategy: transition } }; const operation = await client.command('bind', `.switchyard/generated/${detail.deployment}/resolved-deployment.yaml`, extra); setPending(null); const finished = await onOperation(operation); let latest = routes; try { latest = await client.routes(detail.deployment) } catch (error) { report(error) } await refresh().catch(report); setSwitchReport({ consumer, succeeded: finished?.status === 'succeeded', detail: operationDetail(finished), routes: latest }) } catch (error) { setPending(null); report(error); setSwitchReport({ consumer, succeeded: false, detail: error instanceof Error ? error.message : String(error), routes }) } }
  return <>{required.length > 0 && <label>Complete provider group<select aria-label={`Provider group for ${instance}`} value={bindings[instance] ?? ''} onChange={(event) => event.target.value && prepare(event.target.value)}>{!bindings[instance] && <option value="">Unbound — choose a provider group</option>}{compatible.map((group) => <option key={group}>{group}</option>)}</select><span className="help">{bindings[instance] ? `Currently bound to ${bindings[instance]}. ` : 'Currently unbound. '}Only groups providing every required capability are listed. {Object.keys(groups).length - compatible.length} incompatible groups omitted.</span></label>}{pending && <ChangePreview pending={pending} transition={transition} setTransition={setTransition} timeout={timeout} setTimeout={setTimeoutValue} apply={apply} cancel={() => setPending(null)} />}{switchReport && <SwitchResult report={switchReport} close={() => setSwitchReport(null)} />}</>
}

function SwitchResult({ report, close }: { report: SwitchReport; close: () => void }) {
  const matching = report.routes?.bindings.filter((binding) => binding.binding === report.consumer) ?? []
  return <div className="modal-backdrop"><div className="modal change-preview" role="dialog" aria-modal="true" aria-labelledby="switch-result-title"><h2 id="switch-result-title">Connection switch result</h2><p><strong>{report.succeeded ? 'Atomic binding operation succeeded.' : 'Atomic binding operation failed.'}</strong></p><p className="mono">{report.detail}</p>{matching.length === 0 ? <><p>Route status: no durable router observation is available yet.</p>{!report.succeeded && <p>Rollback information: unavailable from route status.</p>}</> : <><h3>Router observations</h3><ul>{matching.map((binding) => { const history = report.routes ? historyFor(report.routes, binding) : []; return <li key={`${binding.router}-${binding.binding}`}><span className="mono">{binding.router}</span> — desired {version(binding.desiredVersion)}; observed {version(binding.observedVersion)}; status {binding.status}; transition {transitionState(binding.transition)}; error {binding.lastErrorCode ?? 'none'}; {rollback(binding, history)}</li> })}</ul></>}<div><button className="primary" onClick={close}>Close report</button></div></div></div>
}

function ChangePreview({ pending, transition, setTransition, timeout, setTimeout, apply, cancel }: { pending: Pending; transition: Transition; setTransition: (value: Transition) => void; timeout: number; setTimeout: (value: number) => void; apply: () => void; cancel: () => void }) {
  const slots = Array.from(new Set([...Object.keys(pending.oldRoutes), ...Object.keys(pending.newRoutes)]))
  return <div className="modal-backdrop"><div className="modal change-preview" role="dialog" aria-modal="true" aria-labelledby="change-title"><h2 id="change-title">Preview complete route replacement</h2><p><strong>{pending.consumer}</strong>: {pending.oldGroup ? <>{pending.oldGroup} → {pending.newGroup}. Snapshot v{pending.version ?? 'unknown'} will be superseded.</> : <>There is no current provider group. Binding to {pending.newGroup} will create the first routes.</>}</p><table><thead><tr><th>Slot</th><th>Old provider</th><th>New provider</th></tr></thead><tbody>{slots.map((slot) => <tr key={slot}><th>{slot}</th><td>{pending.oldRoutes[slot] ?? (pending.oldGroup ? 'none' : 'There is no current provider')}</td><td>{pending.newRoutes[slot] ?? 'none'}</td></tr>)}</tbody></table><label>Existing connections<select value={transition} onChange={(event) => setTransition(event.target.value as Transition)}><option value="close">Close</option><option value="drain">Drain</option><option value="pin">Pin</option></select></label>{transition === 'drain' && <label>Drain timeout (ms)<input type="number" min="0" value={timeout} onChange={(event) => setTimeout(Number(event.target.value))} /></label>}<div><button onClick={cancel}>Cancel</button><button className="primary" onClick={apply}>Apply complete change</button></div></div></div>
}

export function AuthoredConnections({ client, deployment, onSaved, report }: { client: ApiClient; deployment: string; onSaved: () => Promise<void>; report: (error: unknown) => void }) {
  const [definition, setDefinition] = useState<DeploymentDefinition | null>(null); const [spec, setSpec] = useState<ConnectionSpec | null>(null); const [draft, setDraft] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false); const reportRef = useRef(report); reportRef.current = report
  const install = useCallback(async (found: DeploymentDefinition) => { const validation = await client.validateDeployment(deployment, found.yaml); const authored = definitionSpec(validation.preview); if (!authored) throw new Error('Validated definition preview did not include authored connection state.'); setDefinition(found); setSpec(authored); setDraft(authored.bindings ?? {}) }, [client, deployment])
  useEffect(() => { let active = true; void client.definition(deployment).then(async (found) => { if (active) await install(found) }).catch((error) => reportRef.current(error)); return () => { active = false } }, [client, deployment, install])
  if (!definition || !spec) return <section className="authored-connections" aria-label="Desired connections"><h2>Loading desired connections</h2><p>Loading desired/authored state from the deployment definition…</p></section>
  const groups = resolvedGroups(spec.groups); const consumed = consumedSlots(spec); const consumers = connectionConsumers(spec, consumed); const bindings = spec.bindings ?? {}; const routesFor = (consumer: string, group = draft[consumer]) => group && groups[group] ? groups[group] : spec.routes?.[consumer] ?? {}; const compatible = (consumer: string) => Object.entries(groups).filter(([, providers]) => (consumed[consumer] ?? Object.keys(routesFor(consumer))).every((slot) => slot in providers)).map(([name]) => name); const changed = consumers.filter((consumer) => draft[consumer] && draft[consumer] !== bindings[consumer])
  const save = async () => { if (!changed.length) return; setSaving(true); try { let yaml = definition.yaml; for (const consumer of changed) yaml = updateBindingYaml(yaml, consumer, draft[consumer]); const saved = await client.updateDefinitionValidated(deployment, yaml, definition.hash); await install(saved); await onSaved() } catch (error) { report(error) } finally { setSaving(false) } }
  return <section className="authored-connections" aria-label="Desired connections"><div className="patch-toolbar"><div><h2>Desired connections (authored state)</h2><p className="muted">Desired/authored state from the deployment definition, not observed/runtime state. Changes take effect on the next Up.</p></div><button className="primary" disabled={!changed.length || saving} onClick={() => void save()}>{saving ? 'Saving…' : 'Save desired connections'}</button></div>{consumers.length ? <table><caption>Authored desired connection matrix</caption><thead><tr><th scope="col">Consumer</th><th scope="col">Required slots</th><th scope="col">Desired provider group</th><th scope="col">Desired providers</th></tr></thead><tbody>{consumers.map((consumer) => { const routes = routesFor(consumer); return <tr key={consumer}><th scope="row">{consumer}</th><td>{(consumed[consumer] ?? Object.keys(routes)).join(', ') || 'none'}</td><td><select aria-label={`Desired provider group for ${consumer}`} value={draft[consumer] ?? ''} onChange={(event) => setDraft((current) => ({ ...current, [consumer]: event.target.value }))}><option value="" disabled>Unbound — choose a provider group</option>{compatible(consumer).map((group) => <option key={group}>{group}</option>)}</select></td><td>{Object.keys(routes).length ? Object.entries(routes).map(([slot, provider]) => `${slot} → ${provider}`).join(', ') : 'Unbound — no desired provider'}</td></tr> })}</tbody></table> : <p>No authored consumers have consumed service slots.</p>}</section>
}

export function RoutingEditor({ client, deployment, onSaved, onOperation, report }: { client: ApiClient; deployment: string; onSaved: () => Promise<void>; onOperation: (operation: Operation) => void; report: (error: unknown) => void }) {
  const [definition, setDefinition] = useState<DeploymentDefinition | null>(null); const [draft, setDraft] = useState(''); const [validated, setValidated] = useState(false); const [diagnostics, setDiagnostics] = useState<string[]>([]); const [followUp, setFollowUp] = useState<'none' | 'plan' | 'apply'>('none')
  const load = async () => { try { const found = await client.definition(deployment); setDefinition(found); setDraft(found.yaml); setValidated(false) } catch (error) { report(error) } }
  if (!definition) return <section className="routing-panel"><h2>Routing</h2><p>Custom domains, browser identity routes, and managed profiles are edited in the authored definition.</p><button onClick={load}>Load routing definition</button></section>
  const changed = draft !== definition.yaml; const diff = lineDiff(definition.yaml, draft)
  const validate = async () => { try { const result = await client.validateDeployment(deployment, draft); setDiagnostics(result.diagnostics.map((item) => `${item.code} at ${item.path}: ${item.message}`)); setValidated(true) } catch (error) { setValidated(false); report(error) } }
  const save = async () => { try { await client.updateDefinitionValidated(deployment, draft, definition.hash); setValidated(false); if (followUp !== 'none') onOperation(await client.command(followUp, `deployments/${deployment}.yaml`)); await load(); await onSaved() } catch (error) { report(error) } }
  return <section className="routing-panel"><h2>Routing</h2><p>Edit host-router custom-domain listeners, <code>uiRoutes</code>, and <code>managedProfiles</code>. Every save validates the complete deployment first.</p><label>Deployment YAML<textarea className="yaml-editor" value={draft} onChange={(event) => { setDraft(event.target.value); setValidated(false) }} /></label>{changed && <><h3>Full YAML diff</h3><pre className="yaml-diff">{diff}</pre></>}{diagnostics.length > 0 && <ul>{diagnostics.map((diagnostic) => <li key={diagnostic}>{diagnostic}</li>)}</ul>}<label>After saving<select value={followUp} onChange={(event) => setFollowUp(event.target.value as typeof followUp)}><option value="none">Do not reconcile yet</option><option value="plan">Plan</option><option value="apply">Plan and Up</option></select></label><div><button disabled={!changed} onClick={validate}>Validate changes</button><button className="primary" disabled={!changed || !validated} onClick={save}>Apply definition edit</button></div></section>
}

function lineDiff(oldText: string, newText: string) { const oldLines = oldText.split('\n'); const newLines = newText.split('\n'); const output: string[] = []; const length = Math.max(oldLines.length, newLines.length); for (let index = 0; index < length; index += 1) { if (oldLines[index] === newLines[index]) output.push(`  ${oldLines[index] ?? ''}`); else { if (oldLines[index] !== undefined) output.push(`- ${oldLines[index]}`); if (newLines[index] !== undefined) output.push(`+ ${newLines[index]}`) } } return output.join('\n') }
