import { useEffect, useMemo, useState } from 'react'
import type { AdapterRecord, ApiClient, Operation, SourceRecord } from './api'
import SchemaForm from './SchemaForm'

const namePattern = /^[a-z](?:[a-z0-9-]{0,61}[a-z0-9])?$/

export default function DeploymentBuilder({ client, sources, close, saved, onOperation, report }: { client: ApiClient; sources: SourceRecord[]; close: () => void; saved: (name: string) => Promise<void>; onOperation: (operation: Operation) => void; report: (error: unknown) => void }) {
  const [name, setName] = useState(''); const [instance, setInstance] = useState(''); const [block, setBlock] = useState(''); const [source, setSource] = useState(''); const [adapters, setAdapters] = useState<AdapterRecord[]>([]); const [adapter, setAdapter] = useState(''); const [configuration, setConfiguration] = useState<Record<string, unknown>>({}); const [formValid, setFormValid] = useState(true); const [validation, setValidation] = useState<{ valid: boolean; preview: Record<string, unknown> } | null>(null); const [announcement, setAnnouncement] = useState('Builder ready'); const [startAfterSave, setStartAfterSave] = useState(false)
  useEffect(() => { void client.adapters().then(setAdapters).catch(report) }, [])
  const chosen = adapters.find((item) => `${item.kind}:${item.declaration.id ?? ''}` === adapter) ?? adapters[0]
  useEffect(() => { if (chosen && !adapter) setAdapter(`${chosen.kind}:${chosen.declaration.id ?? ''}`) }, [chosen, adapter])
  const yaml = useMemo(() => buildYaml(name, instance, block, source, sources, configuration), [name, instance, block, source, sources, configuration])
  useEffect(() => { setValidation(null) }, [yaml])
  useEffect(() => {
    if (!namePattern.test(name) || !instance || !block || !source || !formValid) return
    const timer = window.setTimeout(() => { void client.validateDeployment(name, yaml).then((result) => { setValidation(result); setAnnouncement('Draft validation passed') }).catch((error) => { setValidation(null); setAnnouncement('Draft validation failed'); report(error) }) }, 350)
    return () => window.clearTimeout(timer)
  }, [name, instance, block, source, formValid, yaml])
  const validate = async () => { try { const result = await client.validateDeployment(name, yaml); setValidation(result); setAnnouncement(`Draft valid: ${String(result.preview.expandedServiceCount ?? 0)} expanded services`) } catch (error) { setValidation(null); setAnnouncement('Draft validation failed'); report(error) } }
  const save = async () => { try { await client.createDeployment(name, yaml); setAnnouncement(`Deployment ${name} saved`); if (startAfterSave) onOperation(await client.command('apply', `deployments/${name}.yaml`)); await saved(name) } catch (error) { report(error) } }
  return <section className="builder"><div className="title-row"><div><p className="eyebrow">Creation flow</p><h1>New deployment</h1></div><button onClick={close}>Close builder</button></div><div className="builder-grid"><form onSubmit={(event) => { event.preventDefault(); void validate() }}><h2>Definition</h2><label>Name<input required pattern="[a-z](?:[a-z0-9-]{0,61}[a-z0-9])?" value={name} onChange={(event) => setName(event.target.value)} /><span className="help">Lowercase DNS label, up to 63 characters.</span></label><label>Instance name<input required value={instance} onChange={(event) => setInstance(event.target.value)} /></label><label>Block name<input required value={block} onChange={(event) => setBlock(event.target.value)} /></label><label>Source<select required value={source} onChange={(event) => setSource(event.target.value)}><option value="">Choose source</option>{sources.map((item) => <option key={item.source.name}>{item.source.name}</option>)}</select></label><label>Execution adapter<select value={adapter} onChange={(event) => { setAdapter(event.target.value); setConfiguration({}) }}>{adapters.map((item) => <option key={`${item.kind}:${item.declaration.id ?? ''}`} value={`${item.kind}:${item.declaration.id ?? ''}`}>{item.kind} · {String(item.declaration.id ?? 'registered')}</option>)}</select></label>{chosen && <SchemaForm schema={chosen.configurationSchema} value={configuration} onChange={(value, valid) => { setConfiguration(value); setFormValid(valid) }} />}<button disabled={!namePattern.test(name) || !instance || !block || !source || !formValid}>Validate draft</button></form><section><h2>Draft YAML</h2><pre className="draft-yaml">{yaml}</pre><h2>Plan preview</h2>{validation ? <dl><dt>Expanded services</dt><dd>{String(validation.preview.expandedServiceCount ?? 0)}</dd><dt>Images/builds, ports, volumes</dt><dd>See generated Compose preview below.</dd><dt>Routes</dt><dd>{JSON.stringify(validation.preview.routes ?? [])}</dd></dl> : <p className="muted">Validate to derive expanded resources and routes.</p>}<label className="check"><input type="checkbox" checked={startAfterSave} onChange={(event) => setStartAfterSave(event.target.checked)} />Run Up after saving</label><button className="primary" disabled={!validation?.valid} onClick={save}>Save deployment</button></section></div><div className="sr-only" aria-live="polite">{announcement}</div></section>
}

function buildYaml(name: string, instance: string, block: string, sourceName: string, sources: SourceRecord[], configuration: Record<string, unknown>) {
  const source = sources.find((item) => item.source.name === sourceName)
  const execution = Object.keys(configuration).length ? configuration : { type: 'container', image: 'replace-me:local' }
  return JSON.stringify({ apiVersion: 'switchyard.dev/v1alpha1', kind: 'Deployment', metadata: { name }, spec: { sources: sourceName && source ? { [sourceName]: { path: source.source.path } } : {}, blocks: block ? { [block]: { services: { main: { execution } } } } : {}, instances: instance && block && sourceName ? [{ name: instance, block, source: sourceName, parameters: {} }] : [], groups: {}, bindings: {}, routes: {}, uiRoutes: {}, managedProfiles: {} } }, null, 2)
}

export function BlockLibrary({ adapters }: { adapters: AdapterRecord[] }) {
  return <section><h1>Block library</h1><p>Registered execution and probe adapters. Forms are generated directly from each draft 2020-12 configuration schema.</p><div className="adapter-list">{adapters.map((adapter) => <article key={`${adapter.kind}:${adapter.declaration.id ?? ''}`}><h2>{String(adapter.declaration.id ?? adapter.kind)}</h2><p>{adapter.kind} · v{String(adapter.declaration.version ?? 'unknown')}</p><p>Capabilities: {Array.isArray(adapter.declaration.capabilities) ? adapter.declaration.capabilities.join(', ') : 'declared by adapter'}</p><SchemaForm readOnly schema={adapter.configurationSchema} /></article>)}</div></section>
}
