import { useMemo, useState } from 'react'
import type { ApiClient, DeploymentDefinition, DeploymentDetail, Operation, RouteState } from './api'

type Pending = { consumer: string; oldGroup: string; newGroup: string; oldRoutes: Record<string, string>; newRoutes: Record<string, string>; version: number | null }
type Transition = 'close' | 'drain' | 'pin'
const colors: Record<string, string> = { java: '#2457D6', backend: '#2457D6', python: '#7651C9', suite: '#7651C9', database: '#B25C32' }
const cableColor = (slot: string, protocol = '') => Object.entries(colors).find(([name]) => slot.toLowerCase().includes(name))?.[1] ?? ({ tcp: '#B25C32', grpc: '#7651C9' }[protocol] ?? '#2457D6')
const short = (value?: string | null) => value ? value.slice(0, 9) : 'unknown'

function resolvedGroups(groups?: Record<string, { extends?: string; providers?: Record<string, string> }>) {
  const source = (groups ?? {}) as Record<string, { extends?: string; providers?: Record<string, string> }>; const result: Record<string, Record<string, string>> = {}
  const resolve = (name: string, seen = new Set<string>()): Record<string, string> => { if (seen.has(name)) return {}; seen.add(name); const group = source[name]; return group ? { ...(group.extends ? resolve(group.extends, seen) : {}), ...(group.providers ?? {}) } : {} }
  for (const name of Object.keys(source)) result[name] = resolve(name)
  return result
}

export default function DeploymentWorkspace({ client, detail, routes, onOperation, refresh, report }: { client: ApiClient; detail: DeploymentDetail; routes: RouteState | null; onOperation: (operation: Operation) => void; refresh: () => Promise<void>; report: (error: unknown) => void }) {
  const [table, setTable] = useState(false); const [selected, setSelected] = useState(''); const [pending, setPending] = useState<Pending | null>(null); const [transition, setTransition] = useState<Transition>('close'); const [timeout, setTimeoutValue] = useState(30000)
  const spec = detail.snapshot?.spec ?? {}; const groups = useMemo(() => resolvedGroups(spec.groups), [spec.groups]); const bindings = spec.bindings ?? detail.bindings; const direct = spec.routes ?? {}
  const routesFor = (consumer: string, group = bindings[consumer]) => group && groups[group] ? groups[group] : direct[consumer] ?? {}
  const consumers = Array.from(new Set([...Object.keys(direct), ...Object.keys(bindings), ...Object.keys(spec.uiRoutes ?? {})])); const instances = spec.instances ?? Object.keys(detail.sourceIdentities).map((name) => ({ name })); const providers = new Set<string>()
  for (const consumer of consumers) for (const target of Object.values(routesFor(consumer))) providers.add(target.split('/')[0])
  const compatible = (consumer: string) => { const slots = Object.keys(routesFor(consumer)); return Object.entries(groups).filter(([, providers]) => slots.every((slot) => slot in providers)).map(([name]) => name) }
  const prepare = (consumer: string, newGroup: string) => setPending({ consumer, oldGroup: bindings[consumer] ?? 'direct routes', newGroup, oldRoutes: routesFor(consumer), newRoutes: routesFor(consumer, newGroup), version: routes?.bindings.find((route) => route.binding === consumer)?.currentVersion ?? null })
  const apply = async () => { if (!pending) return; try { const extra: Record<string, unknown> = { consumer: pending.consumer, group: pending.newGroup, transition: transition === 'drain' ? { strategy: 'drain', timeoutMs: timeout } : { strategy: transition } }; const operation = await client.command('bind', `.switchyard/generated/${detail.deployment}/resolved-deployment.yaml`, extra); onOperation(operation); setPending(null); await refresh() } catch (error) { report(error) } }
  const identity = selected ? detail.sourceIdentities[selected] : undefined; const selectedRoutes = selected ? routesFor(selected) : {}
  return <>
    <div className="patch-toolbar"><h2>Live patch bay</h2><label className="check"><input type="checkbox" checked={table} onChange={(event) => setTable(event.target.checked)} />Route matrix table</label></div>
    <div className={table ? 'patch-bay table-mode' : 'patch-bay'}>
      <div className="lane"><h3>UI consumers</h3>{consumers.map((name) => <button className="patch-node" key={name} onClick={() => setSelected(name)}><strong>{name}</strong><small>{detail.sourceIdentities[name]?.commit?.slice(0, 7) ?? 'unknown'}</small></button>)}</div>
      <svg className="cables" role="img" aria-label="Route cables" viewBox="0 0 600 360" preserveAspectRatio="none"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="context-stroke" /></marker></defs>{consumers.flatMap((consumer, ci) => Object.entries(routesFor(consumer)).map(([slot, target], ri) => <path key={`${consumer}-${slot}`} data-slot={slot} aria-label={`${consumer} ${slot} to ${target}`} d={`M 20 ${55 + ci * 72} C 190 ${55 + ci * 72}, 390 ${55 + (ri + ci) * 52}, 580 ${55 + (ri + ci) * 52}`} stroke={cableColor(slot)} markerEnd="url(#arrow)" />))}</svg>
      <div className="lane provider-lane"><h3>Backends & providers</h3>{instances.filter((instance) => providers.has(instance.name)).map((instance) => <button className="patch-node" key={instance.name} onClick={() => setSelected(instance.name)}><strong>{instance.name}</strong><small>{short(detail.sourceIdentities[instance.name]?.commit)}</small></button>)}</div>
      <div className="lane group-lane"><h3>Provider groups</h3>{Object.entries(groups).map(([name, members]) => <button className="patch-node" key={name} onClick={() => setSelected(name)}><strong>{name}</strong><small>{Object.keys(members).length} services</small></button>)}</div>
      <table className="route-matrix"><caption>Accessible route matrix</caption><thead><tr><th>Consumer</th><th>Slot</th><th>Provider</th><th>Capability</th></tr></thead><tbody>{consumers.flatMap((consumer) => Object.entries(routesFor(consumer)).map(([slot, provider]) => <tr key={`${consumer}-${slot}`}><th>{consumer}</th><td><span className="capability-key" style={{ '--capability': cableColor(slot) } as React.CSSProperties} />{slot}</td><td>{provider}</td><td>compatible</td></tr>))}</tbody></table>
    </div>
    <section className="node-inspector" aria-label="Instance inspector"><h2>Instance inspector</h2>{selected ? <><h3>{selected}</h3>{identity && <dl><dt>Source</dt><dd className="mono">{identity.path}</dd><dt>Commit</dt><dd className="mono">{short(identity.commit)}</dd><dt>Health</dt><dd>{detail.resources.find((resource) => resource.name.includes(selected))?.state ?? 'unknown'}</dd></dl>}<h3>Active routes</h3>{Object.keys(selectedRoutes).length ? <dl>{Object.entries(selectedRoutes).map(([slot, provider]) => <div key={slot}><dt>{slot}</dt><dd>{provider}</dd></div>)}</dl> : <p className="muted">No consumer routes.</p>}{bindings[selected] && <label>Complete provider group<select aria-label={`Provider group for ${selected}`} value={bindings[selected]} onChange={(event) => prepare(selected, event.target.value)}>{compatible(selected).map((group) => <option key={group}>{group}</option>)}</select><span className="help">Only groups providing every required capability are listed. {Object.keys(groups).length - compatible(selected).length} incompatible groups omitted.</span></label>}</> : <p>Select a node to inspect source, health, resources, and routes.</p>}</section>
    {pending && <ChangePreview pending={pending} transition={transition} setTransition={setTransition} timeout={timeout} setTimeout={setTimeoutValue} apply={apply} cancel={() => setPending(null)} />}
  </>
}

function ChangePreview({ pending, transition, setTransition, timeout, setTimeout, apply, cancel }: { pending: Pending; transition: Transition; setTransition: (value: Transition) => void; timeout: number; setTimeout: (value: number) => void; apply: () => void; cancel: () => void }) {
  const slots = Array.from(new Set([...Object.keys(pending.oldRoutes), ...Object.keys(pending.newRoutes)]))
  return <div className="modal-backdrop"><div className="modal change-preview" role="dialog" aria-modal="true" aria-labelledby="change-title"><h2 id="change-title">Preview complete route replacement</h2><p><strong>{pending.consumer}</strong>: {pending.oldGroup} → {pending.newGroup}. Snapshot v{pending.version ?? 'unknown'} will be superseded.</p><table><thead><tr><th>Slot</th><th>Old provider</th><th>New provider</th></tr></thead><tbody>{slots.map((slot) => <tr key={slot}><th>{slot}</th><td>{pending.oldRoutes[slot] ?? 'none'}</td><td>{pending.newRoutes[slot] ?? 'none'}</td></tr>)}</tbody></table><label>Existing connections<select value={transition} onChange={(event) => setTransition(event.target.value as Transition)}><option value="close">Close</option><option value="drain">Drain</option><option value="pin">Pin</option></select></label>{transition === 'drain' && <label>Drain timeout (ms)<input type="number" min="0" value={timeout} onChange={(event) => setTimeout(Number(event.target.value))} /></label>}<div><button onClick={cancel}>Cancel</button><button className="primary" onClick={apply}>Apply complete change</button></div></div></div>
}

export function RoutingEditor({ client, deployment, onSaved, onOperation, report }: { client: ApiClient; deployment: string; onSaved: () => Promise<void>; onOperation: (operation: Operation) => void; report: (error: unknown) => void }) {
  const [definition, setDefinition] = useState<DeploymentDefinition | null>(null); const [draft, setDraft] = useState(''); const [validated, setValidated] = useState(false); const [diagnostics, setDiagnostics] = useState<string[]>([]); const [followUp, setFollowUp] = useState<'none' | 'plan' | 'apply'>('none')
  const load = async () => { try { const found = await client.definition(deployment); setDefinition(found); setDraft(found.yaml); setValidated(false) } catch (error) { report(error) } }
  if (!definition) return <section className="routing-panel"><h2>Routing</h2><p>Custom domains, browser identity routes, and managed profiles are edited in the authored definition.</p><button onClick={load}>Load routing definition</button></section>
  const changed = draft !== definition.yaml; const diff = lineDiff(definition.yaml, draft)
  const validate = async () => { try { const result = await client.validateDeployment(deployment, draft); setDiagnostics(result.diagnostics.map((item) => `${item.code} at ${item.path}: ${item.message}`)); setValidated(true) } catch (error) { setValidated(false); report(error) } }
  const save = async () => { try { await client.updateDefinitionValidated(deployment, draft, definition.hash); setValidated(false); if (followUp !== 'none') onOperation(await client.command(followUp, `deployments/${deployment}.yaml`)); await load(); await onSaved() } catch (error) { report(error) } }
  return <section className="routing-panel"><h2>Routing</h2><p>Edit host-router custom-domain listeners, <code>uiRoutes</code>, and <code>managedProfiles</code>. Every save validates the complete deployment first.</p><label>Deployment YAML<textarea className="yaml-editor" value={draft} onChange={(event) => { setDraft(event.target.value); setValidated(false) }} /></label>{changed && <><h3>Full YAML diff</h3><pre className="yaml-diff">{diff}</pre></>}{diagnostics.length > 0 && <ul>{diagnostics.map((diagnostic) => <li key={diagnostic}>{diagnostic}</li>)}</ul>}<label>After saving<select value={followUp} onChange={(event) => setFollowUp(event.target.value as typeof followUp)}><option value="none">Do not reconcile yet</option><option value="plan">Plan</option><option value="apply">Plan and Up</option></select></label><div><button disabled={!changed} onClick={validate}>Validate changes</button><button className="primary" disabled={!changed || !validated} onClick={save}>Apply definition edit</button></div></section>
}

function lineDiff(oldText: string, newText: string) { const oldLines = oldText.split('\n'); const newLines = newText.split('\n'); const output: string[] = []; const length = Math.max(oldLines.length, newLines.length); for (let index = 0; index < length; index += 1) { if (oldLines[index] === newLines[index]) output.push(`  ${oldLines[index] ?? ''}`); else { if (oldLines[index] !== undefined) output.push(`- ${oldLines[index]}`); if (newLines[index] !== undefined) output.push(`+ ${newLines[index]}`) } } return output.join('\n') }
