import type { DeploymentSignal, HomeDestination } from './homeModel'
import { projectProblems, setupChecklist } from './homeModel'
import type { DeviceRecord, Operation, ProfileRecord, ProjectInfo, SourceRecord } from './api'

const categories = ['Sources', 'Profiles', 'Deployments', 'Devices', 'Operations', 'Connections'] as const

export default function HomeView({ project, sources, profiles, profileSourceErrors, deployments, devices, operations, loading, unavailable, navigate }: { project: ProjectInfo | null; sources: SourceRecord[]; profiles: ProfileRecord[]; profileSourceErrors: Array<{ source: string; message: string }>; deployments: DeploymentSignal[]; devices: DeviceRecord[]; operations: Operation[]; loading: { sources: boolean; profiles: boolean; deployments: boolean; devices: boolean; operations: boolean }; unavailable: { sources: boolean; profiles: boolean; deployments: boolean; devices: boolean; operations: boolean }; navigate: (destination: HomeDestination) => void }) {
  const checklist = setupChecklist({ sources, profiles, deployments, sourcesLoading: loading.sources, profilesLoading: loading.profiles, deploymentsLoading: loading.deployments, sourcesUnavailable: unavailable.sources, profilesUnavailable: unavailable.profiles, deploymentsUnavailable: unavailable.deployments }); const next = checklist.find((step) => step.state !== 'done'); const problems = projectProblems({ sources, profileSourceErrors, deployments, devices, operations })
  return <section className="home-view"><div className="title-row"><div><p className="eyebrow">Project home</p><h1>{project?.name ?? 'APM ProjectRunner project'}</h1><p className="muted mono">{project?.root ?? 'Loading project identity…'}</p></div></div>
    <section className="home-panel" aria-labelledby="setup-progress-title"><h2 id="setup-progress-title">Setup progress</h2><ol className="setup-checklist">{checklist.map((step) => <li key={step.label} data-state={step.state}><strong><span aria-hidden="true">{step.state === 'done' ? '✓' : step.state === 'unknown' ? '?' : '○'}</span> {step.label}</strong><span>{step.state === 'done' ? 'Complete' : step.state === 'unknown' ? 'Unavailable / unknown' : 'Not complete'}</span><small>{step.signal}</small></li>)}</ol>{next ? <div className="next-action"><p><strong>Next recommended action</strong></p><button className="primary" onClick={() => navigate(next.destination)}>{next.state === 'unknown' ? `Review ${next.label.toLocaleLowerCase()}` : next.action}</button></div> : <div className="next-action"><p><strong>Setup complete</strong></p><button onClick={() => navigate('operations')}>Review operations</button></div>}</section>
    <section className="home-panel" aria-labelledby="project-problems-title"><h2 id="project-problems-title">Project-wide problems</h2>{categories.map((category) => { const matches = problems.filter((problem) => problem.category === category); const signalUnavailable = category === 'Sources' ? loading.sources || unavailable.sources : category === 'Profiles' ? loading.profiles || unavailable.profiles : (category === 'Deployments' || category === 'Connections') ? loading.deployments || unavailable.deployments || deployments.some((deployment) => Boolean(deployment.error)) : category === 'Devices' ? loading.devices || unavailable.devices : loading.operations || unavailable.operations; return <section className="problem-category" key={category}><h3>{category}</h3>{signalUnavailable && <p className="muted">This problem signal is unavailable or incomplete.</p>}{matches.length ? <ul>{matches.map((problem, index) => <li key={`${problem.message}-${index}`}>{problem.message} <button onClick={() => navigate(problem.destination)}>Review</button></li>)}</ul> : !signalUnavailable && <p className="muted">No problems found from the loaded {category.toLocaleLowerCase()} signal.</p>}</section> })}</section>
  </section>
}
